[app]
title = AutoTicket
package.name = autoticket
package.domain = org.autoticket
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
version = 1.0.0
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py
requirements = python3,kivy==2.3.0,pycryptodome,pycryptodomex,requests,pyqrcode,pillow,urllib3
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.1.0
fullscreen = 0
presplash =
icon =
android.api = 34
android.minapi = 21
android.sdk = 34
android.ndk = 25c
android.gradle_dependencies = 'com.android.support:multidex:1.0.3'
android.add_src =
android.permissions = INTERNET, ACCESS_NETWORK_STATE
android.manifest_intent_filter =
android.arch = arm64-v8a
android.extra_java_deps =
android.add_libs_armeabi =
android.add_libs_armeabi_v7a =
android.add_libs_arm64_v8a =
android.add_libs_x86 =
android.add_libs_x86_64 =
android.wakelock = True
android.library_references =
android.ndk_path =
android.sdk_path =
android.ant_path =
android.boot_component =
android.add_activity =
android.add_service =
android.add_receiver =
android.add_provider =
android.add_activity_meta_data =
android.copy_libs =
android.background = 1
android.blacklist =
android.whitelist =
android.pins =
android.dir =
android.allow_backup =
android.store =
android.key =
android.keyalias =
android.store_password =
android.key_password =
android.manifest =
android.res_sources =
android.transparent_background =
android.with_rectangular_image =
android.use_headless_surface =
android.keep_uuid =
android.use_screen =
android.use_camera =
android.use_default_activities =
android.use_analytics =
android.use_internet = True
android.use_wakelock = True
android.use_video =
android.use_webview =
android.use_billing =
android.use_opengl_es2 = True
android.service =
android.activity =
android.ignore_origin =
android.ignore_origin_patterns =
android.native_service =
android.native_service_args =
android.verify_local_cert =
android.verify_remote_cert =
android.min_sdk = 21
android.target_sdk = 34
android.manifest_placeholders =
p4a.sdk_dir =
p4a.ndk_dir =
p4a.branch = develop
p4a.local_recipes =
p4a.hooks =
p4a.requirements =
p4a.source_dir =
p4a.archs = arm64-v8a
p4a.android_api = 34
p4a.ndk_api = 21
p4a.sdk_manager_version =
p4a.append_args =
p4a.bootstrap =
p4a.bootstrap_dir =
p4a.debug =
p4a.verbose =
p4a.generate_presplash = True
p4a.dir =
p4a.ignore_origin =
p4a.icon =
p4a.private_storage =
p4a.window = True
p4a.xwindow =
p4a.xscreen =
p4a.xvideo =
p4a.xcursor =
p4a.xcursor_theme =
p4a.xcursor_size =
p4a.xkb_layout =
p4a.xkb_variant =
p4a.xkb_options =
p4a.xkb_model =
p4a.xkb_rules =
p4a.xkb_loading_animation =
p4a.xkb_animation =

[buildozer]
log_level = 2
warn_on_root = 0
